# Generated by Django 5.1.1 on 2025-08-01 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_orderfeedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='related_order',
        ),
        migrations.AddField(
            model_name='notification',
            name='related_object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_object_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('order_new', 'سفارش جدید'), ('order_status', 'تغییر وضعیت سفارش'), ('low_stock', 'موجودی کم'), ('feedback_new', 'بازخورد جدید'), ('user_new', 'کاربر جدید'), ('system', 'سیستم')], max_length=20),
        ),
    ]
