# Generated by Django 5.1.1 on 2025-08-05 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_update_order_status_choices'),
        ('shop', '0012_alter_userprofile_options_and_more'),
    ]

    operations = [

        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(
                max_length=25,
                choices=[
                    ('pending_payment', 'در انتظار پرداخت'),
                    ('preparing', 'در حال آمــاده‌سازی'),
                    ('ready', 'آماده شده'),
                    ('shipping_preparation', 'در حال ارسال به اداره پست'),
                    ('in_transit', 'بسته در حال رسیدن به مقصد است'),
                    ('pickup_ready', 'آماده شده است و لطفاً مراجعه کنید'),
                ],
                default='pending_payment',
            ),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(
                max_length=20,
                choices=[
                    ('pickup', 'دریافت حضوری'),
                    ('postal', 'ارسال پستی'),
                ],
                default='pickup',
            ),
        ),

    ]
