# Generated by Django 5.1.1 on 2025-08-07 07:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_add_product_grind_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('view', 'مشاهده'), ('like', 'پسندیدن'), ('favorite', 'علاقه\u200cمندی'), ('cart_add', 'افزودن به سبد'), ('purchase', 'خرید'), ('review', 'نظردهی')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session_id', models.CharField(blank=True, max_length=40)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.RemoveField(
            model_name='analyticsevent',
            name='category',
        ),
        migrations.RemoveField(
            model_name='analyticsevent',
            name='order',
        ),
        migrations.RemoveField(
            model_name='analyticsevent',
            name='product',
        ),
        migrations.RemoveField(
            model_name='analyticsevent',
            name='user',
        ),
        migrations.RemoveField(
            model_name='pushsubscription',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='customersegment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='loyaltyprogram',
            options={},
        ),
        migrations.AlterModelOptions(
            name='productrecommendation',
            options={'ordering': ['-score', '-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='useractivity',
            name='shop_userac_user_id_ba15d1_idx',
        ),
        migrations.RemoveIndex(
            model_name='useractivity',
            name='shop_userac_action_3d8499_idx',
        ),
        migrations.RenameField(
            model_name='loyaltyprogram',
            old_name='created_at',
            new_name='tier_achieved_date',
        ),
        migrations.RenameField(
            model_name='loyaltyprogram',
            old_name='points_earned',
            new_name='total_earned_points',
        ),
        migrations.RenameField(
            model_name='loyaltyprogram',
            old_name='points_redeemed',
            new_name='total_redeemed_points',
        ),
        migrations.RenameField(
            model_name='searchquery',
            old_name='filters_applied',
            new_name='filters_used',
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='customersegment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='loyaltyprogram',
            name='total_spent',
        ),
        migrations.RemoveField(
            model_name='loyaltyprogram',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='grind_type',
            field=models.CharField(choices=[('whole_bean', 'دانه کامل'), ('coarse', 'درشت (فرنچ پرس)'), ('medium_coarse', 'متوسط درشت (کمکس)'), ('medium', 'متوسط (دریپ)'), ('medium_fine', 'متوسط ریز (اروپرس)'), ('fine', 'ریز (اسپرسو)'), ('extra_fine', 'فوق ریز (ترک)')], default='whole_bean', max_length=20),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='weight',
            field=models.CharField(choices=[('250g', '250 گرم'), ('500g', '500 گرم'), ('1kg', '1 کیلوگرم'), ('5kg', '5 کیلوگرم'), ('10kg', '10 کیلوگرم')], default='250g', max_length=10),
        ),
        migrations.AddField(
            model_name='customersegment',
            name='engagement_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='loyaltyprogram',
            name='next_tier_points_needed',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='productrecommendation',
            name='recommendation_type',
            field=models.CharField(default='similar', max_length=50),
        ),
        migrations.AddField(
            model_name='searchquery',
            name='clicked_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.product'),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='user_agent',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='customersegment',
            name='average_order_value',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='customersegment',
            name='segment_type',
            field=models.CharField(choices=[('vip', 'مشتری VIP'), ('regular', 'مشتری عادی'), ('new', 'مشتری جدید'), ('inactive', 'غیرفعال'), ('coffee_enthusiast', 'علاقه\u200cمند به قهوه'), ('dessert_lover', 'علاقه\u200cمند به دسر'), ('price_sensitive', 'حساس به قیمت'), ('premium_buyer', 'خریدار لوکس')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='customersegment',
            name='total_spent',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='loyaltyprogram',
            name='tier',
            field=models.CharField(choices=[('bronze', 'برنزی'), ('silver', 'نقره\u200cای'), ('gold', 'طلایی'), ('platinum', 'پلاتینیوم')], default='bronze', max_length=20),
        ),
        migrations.AlterField(
            model_name='productrecommendation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product'),
        ),
        migrations.AlterField(
            model_name='searchquery',
            name='query',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='searchquery',
            name='session_id',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='searchquery',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.category'),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.product'),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product', 'grind_type', 'weight')},
        ),
        migrations.AddIndex(
            model_name='customersegment',
            index=models.Index(fields=['segment_type'], name='shop_custom_segment_59264f_idx'),
        ),
        migrations.AddIndex(
            model_name='customersegment',
            index=models.Index(fields=['total_spent'], name='shop_custom_total_s_14e76c_idx'),
        ),
        migrations.AddIndex(
            model_name='customersegment',
            index=models.Index(fields=['engagement_score'], name='shop_custom_engagem_2e29ea_idx'),
        ),
        migrations.AddIndex(
            model_name='loyaltyprogram',
            index=models.Index(fields=['tier', '-points'], name='shop_loyalt_tier_031382_idx'),
        ),
        migrations.AddIndex(
            model_name='productrecommendation',
            index=models.Index(fields=['user', '-score'], name='shop_produc_user_id_530f8b_idx'),
        ),
        migrations.AddIndex(
            model_name='productrecommendation',
            index=models.Index(fields=['recommendation_type', '-created_at'], name='shop_produc_recomme_a0af79_idx'),
        ),
        migrations.AddIndex(
            model_name='searchquery',
            index=models.Index(fields=['query', '-timestamp'], name='shop_search_query_90d43c_idx'),
        ),
        migrations.AddIndex(
            model_name='searchquery',
            index=models.Index(fields=['user', '-timestamp'], name='shop_search_user_id_30e7ee_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['user', '-timestamp'], name='shop_userac_user_id_f21885_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['action', '-timestamp'], name='shop_userac_action_1dd329_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['product', '-timestamp'], name='shop_userac_product_70469e_idx'),
        ),
        migrations.AddField(
            model_name='productinteraction',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='shop.product'),
        ),
        migrations.AddField(
            model_name='productinteraction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_interactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='AnalyticsEvent',
        ),
        migrations.DeleteModel(
            name='PushSubscription',
        ),
        migrations.AddIndex(
            model_name='productinteraction',
            index=models.Index(fields=['user', 'interaction_type', '-timestamp'], name='shop_produc_user_id_a75c01_idx'),
        ),
        migrations.AddIndex(
            model_name='productinteraction',
            index=models.Index(fields=['product', 'interaction_type', '-timestamp'], name='shop_produc_product_e03795_idx'),
        ),
    ]
