# Generated by Django 5.1.1 on 2025-08-07 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_add_order_item_grind_weight_fields'),
        ('shop', '0015_productinteraction_remove_analyticsevent_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='grind_type',
            field=models.CharField(
                choices=[
                    ('whole_bean', 'اسیاب نشده'),
                    ('coarse', 'ترک'),
                    ('medium_coarse', 'موکاپات'),
                    ('medium', 'اسپرسو ساز نیمه صنعتی'),
                    ('medium_fine', 'اسپرسوساز صنعتی'),
                    ('fine', 'اسپرسوساز خانگی'),
                ],
                default='whole_bean',
                max_length=20
            ),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='weight',
            field=models.CharField(
                choices=[
                    ('250g', '250 گرم'),
                    ('500g', '500 گرم'),
                    ('1kg', '1 کیلوگرم'),
                    ('5kg', '5 کیلوگرم'),
                    ('10kg', '10 کیلوگرم'),
                ],
                default='250g',
                max_length=10
            ),
        ),
    ]
