# Generated by Django 5.1.1 on 2025-08-07 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_add_order_item_grind_weight_fields'),
        ('shop', '0015_productinteraction_remove_analyticsevent_category_and_more'),
    ]

    operations = []
