# Generated by Django 5.1.1 on 2025-08-09 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='grind_type',
            field=models.CharField(choices=[('whole_bean', 'اسیاب نشده'), ('coarse', 'ترک'), ('medium_coarse', 'موکاپات'), ('medium', 'اسپرسو ساز نیمه صنعتی'), ('medium_fine', 'اسپرسوساز صنعتی'), ('fine', 'اسپرسوساز خانگی')], default='whole_bean', max_length=20),
        ),
    ]
