# Generated by Django 5.1.1 on 2025-08-09 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_cartitem_add_grind_weight_and_unique'),
        ('shop', '0017_alter_cartitem_grind_type'),
    ]

    operations = [
    ]
