# Generated by Django 5.1.1 on 2025-08-09 10:15


from django.db import migrations

class Migration(migrations.Migration):
     dependencies = [ ('shop', '0018_merge_20250809_0301'), ] 
     operations = [ migrations.RunSQL( "CREATE UNIQUE INDEX IF NOT EXISTS shop_cartitem_unique " "ON shop_cartitem (cart_id, product_id, grind_type, weight);", "DROP INDEX IF EXISTS shop_cartitem_unique;", ), ] 