# Generated by Django 5.1.1 on 2025-08-09 10:15


from django.db import migrations

class Migration(migrations.Migration):
     dependencies = [ ('shop', '0018_merge_20250809_0301'), ] 
     # This migration used to add a redundant unique index overlapping unique_together.
     # It is now a no-op to avoid duplicate indexes while retaining migration order.
     operations = []