# Generated by Django 5.1.1 on 2025-08-09 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_alter_order_delivery_method_post_only'),
        ('shop', '0019_ensure_cartitem_unique_index'),
    ]

    operations = [
    ]
