# Generated by Django 5.1.1 on 2025-08-10 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_add_slugs'),
        ('shop', '0020_merge_20250809_0418'),
        ('shop', '0021_merge_0018_add_slugs_0020_merge_20250809_0418'),
    ]

    operations = [
    ]
