# Generated by Django 5.1.1 on 2025-08-12 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_merge_20250810_0628'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': (('view_advanced_analytics', 'Can view advanced analytics'), ('export_data', 'Can export analytics data'), ('manage_promotions', 'Can manage promotions and campaigns'))},
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=160, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=220, unique=True),
        ),
    ]
