# Generated by Django 5.1.1 on 2025-08-12 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_alter_order_options_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='weight',
            field=models.CharField(choices=[('100g', '100 گرم'), ('250g', '250 گرم'), ('500g', '500 گرم'), ('1kg', '1 کیلوگرم'), ('5kg', '5 کیلوگرم'), ('10kg', '10 کیلوگرم')], default='250g', max_length=10),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='weight',
            field=models.CharField(choices=[('100g', '100 گرم'), ('250g', '250 گرم'), ('500g', '500 گرم'), ('1kg', '1 کیلوگرم'), ('5kg', '5 کیلوگرم'), ('10kg', '10 کیلوگرم')], default='250g', max_length=10),
        ),
    ]
