# Generated by Django 5.1.1 on 2025-08-13 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_alter_cartitem_weight_alter_orderitem_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='intro_margin_applied_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='اعتبار خوش\u200cآمدگویی اعمال شده'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='intro_margin_awarded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='intro_margin_balance',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='اعتبار خوش\u200cآمدگویی'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='intro_margin_consumed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_phone_verified',
            field=models.BooleanField(db_index=True, default=False, verbose_name='شماره تایید شده'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_verify_code',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_verify_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
